/* Auto-generated by aeroguard_sim.py - Random Forest crash classifier for STM32 (no dependencies).
   Feature order:  a_mean, a_min, a_max, a_std, freefall_frac, vib_rms, jerk_mean, jerk_max, g_mean, g_max, g_std, tilt, tilt_delta
   Returns crash probability in [0,1]. */
#ifndef CRASH_MODEL_H
#define CRASH_MODEL_H

static inline float tree_0(const float *x) {
  if (x[4] <= 0.01000f) {
    if (x[1] <= 0.64675f) {
      if (x[10] <= 9.58302f) {
        if (x[1] <= 0.59962f) {
          return 1.0000f;
        } else {
          return 0.4286f;
        }
      } else {
        return 1.0000f;
      }
    } else {
      if (x[2] <= 1.09322f) {
        if (x[0] <= 0.98530f) {
          if (x[8] <= 42.14211f) {
            return 0.0000f;
          } else {
            if (x[1] <= 0.81537f) {
              return 0.0000f;
            } else {
              return 0.4444f;
            }
          }
        } else {
          if (x[3] <= 0.04154f) {
            return 1.0000f;
          } else {
            return 0.9048f;
          }
        }
      } else {
        if (x[8] <= 5.76633f) {
          return 1.0000f;
        } else {
          if (x[3] <= 0.04948f) {
            return 1.0000f;
          } else {
            if (x[2] <= 5.13717f) {
              return 0.0036f;
            } else {
              return 1.0000f;
            }
          }
        }
      }
    }
  } else {
    return 1.0000f;
  }
}
static inline float tree_1(const float *x) {
  if (x[3] <= 0.05974f) {
    if (x[0] <= 1.01149f) {
      if (x[2] <= 0.85511f) {
        return 1.0000f;
      } else {
        if (x[3] <= 0.05068f) {
          return 1.0000f;
        } else {
          return 0.0000f;
        }
      }
    } else {
      if (x[7] <= 21.56221f) {
        return 0.2857f;
      } else {
        return 0.0000f;
      }
    }
  } else {
    if (x[1] <= 0.64675f) {
      if (x[9] <= 79.69127f) {
        if (x[10] <= 6.23713f) {
          return 1.0000f;
        } else {
          if (x[11] <= 159.74127f) {
            return 0.5556f;
          } else {
            if (x[7] <= 32.02542f) {
              return 0.8333f;
            } else {
              return 1.0000f;
            }
          }
        }
      } else {
        return 1.0000f;
      }
    } else {
      if (x[1] <= 0.65638f) {
        if (x[8] <= 79.63083f) {
          return 0.6250f;
        } else {
          return 0.0000f;
        }
      } else {
        if (x[2] <= 5.13717f) {
          if (x[10] <= 7.01333f) {
            if (x[12] <= -2.08336f) {
              return 0.0037f;
            } else {
              return 0.0000f;
            }
          } else {
            if (x[1] <= 0.76218f) {
              return 0.0437f;
            } else {
              return 0.0028f;
            }
          }
        } else {
          return 1.0000f;
        }
      }
    }
  }
}
static inline float tree_2(const float *x) {
  if (x[10] <= 37.63385f) {
    if (x[8] <= 161.47567f) {
      if (x[8] <= 9.26590f) {
        if (x[8] <= 7.24862f) {
          if (x[1] <= 0.87876f) {
            return 1.0000f;
          } else {
            if (x[5] <= 0.08720f) {
              return 1.0000f;
            } else {
              return 0.6000f;
            }
          }
        } else {
          if (x[1] <= 0.76070f) {
            return 1.0000f;
          } else {
            if (x[3] <= 0.05138f) {
              return 1.0000f;
            } else {
              return 0.0000f;
            }
          }
        }
      } else {
        if (x[7] <= 43.06912f) {
          if (x[4] <= 0.01000f) {
            if (x[0] <= 0.93741f) {
              return 0.1813f;
            } else {
              return 0.0144f;
            }
          } else {
            return 1.0000f;
          }
        } else {
          if (x[8] <= 66.73773f) {
            if (x[3] <= 0.11255f) {
              return 0.8182f;
            } else {
              return 1.0000f;
            }
          } else {
            return 0.4444f;
          }
        }
      }
    } else {
      if (x[2] <= 0.92864f) {
        return 1.0000f;
      } else {
        if (x[6] <= 21.63400f) {
          return 0.0000f;
        } else {
          return 1.0000f;
        }
      }
    }
  } else {
    if (x[1] <= 0.65423f) {
      return 1.0000f;
    } else {
      if (x[7] <= 21.73428f) {
        return 1.0000f;
      } else {
        if (x[2] <= 5.04093f) {
          return 0.0000f;
        } else {
          return 1.0000f;
        }
      }
    }
  }
}
static inline float tree_3(const float *x) {
  if (x[4] <= 0.01000f) {
    if (x[7] <= 45.56121f) {
      if (x[5] <= 0.07638f) {
        return 1.0000f;
      } else {
        if (x[2] <= 0.85049f) {
          return 1.0000f;
        } else {
          if (x[0] <= 0.95853f) {
            if (x[8] <= 60.90930f) {
              return 0.0979f;
            } else {
              return 0.0000f;
            }
          } else {
            if (x[1] <= 0.64608f) {
              return 0.9130f;
            } else {
              return 0.0031f;
            }
          }
        }
      }
    } else {
      return 1.0000f;
    }
  } else {
    return 1.0000f;
  }
}
static inline float tree_4(const float *x) {
  if (x[10] <= 37.05325f) {
    if (x[1] <= 0.64608f) {
      if (x[12] <= -10.64917f) {
        if (x[11] <= 161.36847f) {
          return 1.0000f;
        } else {
          return 0.9091f;
        }
      } else {
        return 1.0000f;
      }
    } else {
      if (x[7] <= 20.22420f) {
        if (x[5] <= 0.06889f) {
          return 1.0000f;
        } else {
          return 0.4545f;
        }
      } else {
        if (x[7] <= 44.55795f) {
          if (x[5] <= 0.08829f) {
            return 0.4286f;
          } else {
            if (x[7] <= 35.30666f) {
              return 0.0025f;
            } else {
              return 0.0369f;
            }
          }
        } else {
          return 0.9000f;
        }
      }
    }
  } else {
    if (x[4] <= 0.01000f) {
      if (x[3] <= 0.70059f) {
        if (x[6] <= 9.60011f) {
          return 1.0000f;
        } else {
          if (x[3] <= 0.05899f) {
            return 1.0000f;
          } else {
            if (x[11] <= 147.43269f) {
              return 0.0000f;
            } else {
              return 0.5714f;
            }
          }
        }
      } else {
        return 1.0000f;
      }
    } else {
      return 1.0000f;
    }
  }
}
static inline float tree_5(const float *x) {
  if (x[1] <= 0.64608f) {
    if (x[12] <= -17.63798f) {
      if (x[2] <= 1.18112f) {
        return 1.0000f;
      } else {
        if (x[1] <= 0.48245f) {
          return 1.0000f;
        } else {
          return 0.9231f;
        }
      }
    } else {
      return 1.0000f;
    }
  } else {
    if (x[3] <= 0.04948f) {
      return 1.0000f;
    } else {
      if (x[2] <= 5.13717f) {
        if (x[1] <= 0.74446f) {
          if (x[9] <= 72.29161f) {
            if (x[7] <= 31.18998f) {
              return 0.4444f;
            } else {
              return 1.0000f;
            }
          } else {
            return 0.0000f;
          }
        } else {
          if (x[0] <= 0.95772f) {
            if (x[1] <= 0.82570f) {
              return 0.0000f;
            } else {
              return 0.0220f;
            }
          } else {
            if (x[9] <= 17.41470f) {
              return 0.0140f;
            } else {
              return 0.0003f;
            }
          }
        }
      } else {
        return 1.0000f;
      }
    }
  }
}
static inline float tree_6(const float *x) {
  if (x[1] <= 0.64675f) {
    if (x[6] <= 13.76361f) {
      return 1.0000f;
    } else {
      if (x[6] <= 13.77074f) {
        return 0.9444f;
      } else {
        if (x[4] <= 0.01000f) {
          if (x[6] <= 14.30663f) {
            if (x[12] <= -13.97045f) {
              return 0.6000f;
            } else {
              return 1.0000f;
            }
          } else {
            if (x[3] <= 0.13581f) {
              return 0.9583f;
            } else {
              return 1.0000f;
            }
          }
        } else {
          return 1.0000f;
        }
      }
    }
  } else {
    if (x[5] <= 0.07800f) {
      return 1.0000f;
    } else {
      if (x[9] <= 192.60229f) {
        if (x[8] <= 6.05490f) {
          return 0.7500f;
        } else {
          if (x[1] <= 0.76218f) {
            if (x[2] <= 1.20305f) {
              return 0.1453f;
            } else {
              return 0.0054f;
            }
          } else {
            if (x[9] <= 17.41470f) {
              return 0.0180f;
            } else {
              return 0.0018f;
            }
          }
        }
      } else {
        if (x[5] <= 0.68445f) {
          return 0.0000f;
        } else {
          return 1.0000f;
        }
      }
    }
  }
}
static inline float tree_7(const float *x) {
  if (x[5] <= 0.22527f) {
    if (x[1] <= 0.64608f) {
      if (x[7] <= 32.72975f) {
        return 1.0000f;
      } else {
        if (x[3] <= 0.12975f) {
          return 1.0000f;
        } else {
          if (x[7] <= 33.29019f) {
            return 0.7857f;
          } else {
            return 1.0000f;
          }
        }
      }
    } else {
      if (x[6] <= 9.69425f) {
        if (x[5] <= 0.06961f) {
          return 1.0000f;
        } else {
          return 0.7273f;
        }
      } else {
        if (x[7] <= 35.30666f) {
          if (x[2] <= 1.20273f) {
            if (x[3] <= 0.11339f) {
              return 0.0042f;
            } else {
              return 0.2500f;
            }
          } else {
            if (x[5] <= 0.11111f) {
              return 0.0008f;
            } else {
              return 0.0000f;
            }
          }
        } else {
          if (x[2] <= 1.11011f) {
            if (x[3] <= 0.07482f) {
              return 0.0000f;
            } else {
              return 0.7692f;
            }
          } else {
            if (x[7] <= 37.86205f) {
              return 0.0045f;
            } else {
              return 0.1098f;
            }
          }
        }
      }
    }
  } else {
    if (x[1] <= 0.64675f) {
      return 1.0000f;
    } else {
      if (x[6] <= 19.61050f) {
        return 0.0000f;
      } else {
        return 1.0000f;
      }
    }
  }
}
static inline float tree_8(const float *x) {
  if (x[4] <= 0.01000f) {
    if (x[7] <= 45.56121f) {
      if (x[2] <= 1.09288f) {
        if (x[6] <= 10.11626f) {
          return 1.0000f;
        } else {
          if (x[1] <= 0.57808f) {
            return 1.0000f;
          } else {
            if (x[2] <= 1.08331f) {
              return 0.0000f;
            } else {
              return 0.0267f;
            }
          }
        }
      } else {
        if (x[1] <= 0.64608f) {
          return 1.0000f;
        } else {
          if (x[9] <= 4.93844f) {
            return 1.0000f;
          } else {
            if (x[3] <= 0.04948f) {
              return 1.0000f;
            } else {
              return 0.0043f;
            }
          }
        }
      }
    } else {
      return 1.0000f;
    }
  } else {
    return 1.0000f;
  }
}
static inline float tree_9(const float *x) {
  if (x[4] <= 0.01000f) {
    if (x[8] <= 172.49905f) {
      if (x[1] <= 0.64675f) {
        if (x[7] <= 32.94381f) {
          if (x[2] <= 1.25096f) {
            if (x[3] <= 0.14210f) {
              return 0.7778f;
            } else {
              return 1.0000f;
            }
          } else {
            return 0.5000f;
          }
        } else {
          return 1.0000f;
        }
      } else {
        if (x[3] <= 0.04948f) {
          return 1.0000f;
        } else {
          if (x[2] <= 5.13717f) {
            if (x[7] <= 37.86205f) {
              return 0.0029f;
            } else {
              return 0.0833f;
            }
          } else {
            return 1.0000f;
          }
        }
      }
    } else {
      return 1.0000f;
    }
  } else {
    return 1.0000f;
  }
}
static inline float tree_10(const float *x) {
  if (x[3] <= 0.05957f) {
    if (x[4] <= 0.01000f) {
      if (x[5] <= 0.07638f) {
        return 1.0000f;
      } else {
        if (x[2] <= 0.85934f) {
          return 1.0000f;
        } else {
          return 0.0000f;
        }
      }
    } else {
      return 1.0000f;
    }
  } else {
    if (x[4] <= 0.01000f) {
      if (x[1] <= 0.64675f) {
        if (x[5] <= 0.22886f) {
          if (x[10] <= 9.58302f) {
            if (x[8] <= 47.53050f) {
              return 1.0000f;
            } else {
              return 0.6250f;
            }
          } else {
            return 1.0000f;
          }
        } else {
          return 1.0000f;
        }
      } else {
        if (x[8] <= 6.44956f) {
          return 0.7778f;
        } else {
          if (x[10] <= 65.83016f) {
            if (x[9] <= 192.89863f) {
              return 0.0046f;
            } else {
              return 0.1111f;
            }
          } else {
            if (x[7] <= 369.86517f) {
              return 0.0000f;
            } else {
              return 1.0000f;
            }
          }
        }
      }
    } else {
      return 1.0000f;
    }
  }
}
static inline float tree_11(const float *x) {
  if (x[4] <= 0.01000f) {
    if (x[6] <= 19.77717f) {
      if (x[2] <= 1.09374f) {
        if (x[3] <= 0.05351f) {
          return 1.0000f;
        } else {
          if (x[0] <= 0.69179f) {
            return 1.0000f;
          } else {
            if (x[0] <= 0.89838f) {
              return 0.2000f;
            } else {
              return 0.0000f;
            }
          }
        }
      } else {
        if (x[7] <= 42.05547f) {
          if (x[6] <= 9.70260f) {
            return 1.0000f;
          } else {
            if (x[9] <= 40.16047f) {
              return 0.0017f;
            } else {
              return 0.0228f;
            }
          }
        } else {
          if (x[7] <= 45.56121f) {
            return 0.6154f;
          } else {
            return 1.0000f;
          }
        }
      }
    } else {
      return 1.0000f;
    }
  } else {
    return 1.0000f;
  }
}

static inline float crash_probability(const float *x) {
  float s = 0.0f;
  s += tree_0(x);
  s += tree_1(x);
  s += tree_2(x);
  s += tree_3(x);
  s += tree_4(x);
  s += tree_5(x);
  s += tree_6(x);
  s += tree_7(x);
  s += tree_8(x);
  s += tree_9(x);
  s += tree_10(x);
  s += tree_11(x);
  return s / 12.0f;
}

#endif
